### ISSUE TITLE
Feature request: Bulma framework support

### ISSUE THREAD

**Issue by YoeriNijs** [fjalvingh/domui#32]
I was wondering whether it is possible to integrate [Bulma CSS framework](https://bulma.io) in DomUI. In my opinion, integration would be nice, because with Bulma it is easy to style components with the latest web standards and without additional javascript. For instance, by adding the css class 'is-primary' to a button, the button will be transformed to a primary button at runtime. Nevertheless, albeit all this glamour, integration could be a messy task, because it might be needed that all current css selectors must be replaced.

**Comment by fjalvingh** [comment]
That looks interesting. I'm busy with restyling a lot in 2.0; once the core is done I'll definitely take a look at this. I am not 100% sure its look is a good fit with business applications (it seems very flat and colorful, especially the latter will get irritating quite quickly I would assume; how does Marc feel about it?)

By itself, with the SASS/SCSS support that is already working fine in 2.0 it should be easy to combine the framework with DomUI..

**Comment by fjalvingh** [comment]
What is an issue, though, is this:
"Internet Explorer (10+) is only partially supported."

**Comment by YoeriNijs** [comment]
Yeah, it looks very colorful, but it is possible to override default styling by customizing Bulma. See https://bulma.io/documentation/overview/customize/

Marc (the designer) thinks it could help to improve DomUI styling. However, he believes that the programmer must not have to much flexibility in styling adjustments. Otherwise one has to check every time a page is created whether all UI components are instantiated correctly. Maybe a way to solve this issue, is to provide some way of default Bulma styling, and provide an option to override it as well.

**Comment by fjalvingh** [comment]
All default DomUI components have a default presentation, and the programmer does not usually change that at all (the only instance I remember is for the case system, where we actually wanted another look ;). That is common for most component based frameworks like DomUI actually. So this framework will not fix anything related to that.
The only issue with "correctly instantiating" is related to browser versions and stylesheet issues: any change to a stylesheet that is used for everything obviously has effect on everything too. That does not change with using a css framework.
What the thing could help with is to get overall layout easier, because that is actually an enormous amount of work. But most of that is not in "the big picture": it is in things like correctly styling very complex components like LookupUnput, for instance (see https://etc.to/confluence/pages/viewpage.action?pageId=10453058). That framework will not help with that, I think?

**Comment by fjalvingh** [comment]
I was wondering: do you have a reason not to look at, for instance, Bootstrap? And have you seen this?

https://material.io/components/web/

that also seems quite interesting.

**Comment by YoeriNijs** [comment]
Yeah, the major idea is to improve overall layout capabilities of DomUI, so programmers can add additional styling, based on web standards, out-of-the-box. Especially, I like the grid system based on css's flexbox, which may able the programmer to add responsive div's next to each other with ease. By the way: it is important to note that I am submitting this request on my behalf, and not on behalf of an organization.

In my opinion, the main reason not to look at Bootstrap or another framework like that in the first place, it that those frameworks require additional Javascript in order to getting it work. Bulma only requires css, which is clean and lightweight.

**Comment by YoeriNijs** [comment]
There is a blogpost on Bulma/Bootstrap comparison: https://bulma.io/2017/08/01/bulma-bootstrap-comparison/

**Comment by fjalvingh** [comment]
Well, I'm looking at the stuff right now ;) Do you have any idea on what you want to do? Because as of now I can only imagine that DomUI components would expose Bulma css classes on themselves instead of their usual ones. But that means a tight fit between DomUI and Bulma... So adding another thing, like Bootstrap or whatever, would not really work..
We could do something like separating behavioral aspects of the component (say the Java side of the thing, with the abilities exposed there) from the rendering aspects, like having a separate rendering agent for each component. But that would be quite a big change..

Ideas?

**Comment by YoeriNijs** [comment]
The first thing you mention is exactly what I meant - although tight fit with Bulma is unassumingly not what you want, because DomUI would be to dependent from a relatively new library, which is above all still under active development... But I still believe this might be the best thing to do if you do believe it could contribute to DomUI.

I believe separating aspects is only wanted if it concerns adding a css library (thus, not a css+js one, because you want to be in control about the behavior, I think). Ideally, you want to make some sort of mapping between the css selectors provided by the external lib and the Java/behavioral side by DomUI. I do not believe it is possible to map these things automatically at once, so one might map them by themselves initially :(

**Comment by fjalvingh** [comment]
Ok, I took a detailed look and did a few changes in DomUI to use some Bulma styles. I think it will be hard to adapt to it, and I wonder how to do something that allows me to "switch" to a Bulma stylesheet without changing all of the css classes on the components. The latter is the biggest issue actually...

If you want more info see https://etc.to/confluence/display/DOM/Playing+with+Bulma

Did you play with it?

**Comment by YoeriNijs** [comment]
I did play with it, but not in combination with DomUI so far. I am using Bulma for a personal web based project, but I recognize your criticism. In particular, for me, Bulma is difficult to combine with other css frameworks that are using Flexbox as well. So, you have to go all in with Bulma, or do not using it at all.

I read your article and I believe you are in the right track regarding the general concepts. It should be not too difficult to adapt Flexbox in DomUI, because it is already part of css and it well documented. Integrating Flexbox might be an enormous step forward already. And by creating the right css selectors for DomUI components globally (is-primary, is-mobile et cetera), it should be easy to use as well. 

I believe, in the end, the DomUI user wants to have to freedom to set the component's style by adding the Bulma-like selectors. Only if he does not add the css selectors, the component itself might set it's own default style. 

N.B. I stumbled upon [ThimbleCSS](https://github.com/agileleague/thimblecss), which seems very Bulma-like. I do not know this, but it is possible that it fits DomUI better. You might want to consider to look at it.

**Comment by fjalvingh** [comment]
Well, I converted Bulma sass code to scss (there appears to be no sass compiler for Java), and I removed most of the silliness from the reset script. That delivers something that at least works... You can try by just launching the demo application and look at the Test pages -> Text2 layout.

I will definitely rethink some of the styling with this experience in mind because by itself the ideas in Bulma are nice, but I will not integrate the framework itself.

It's a pity that I suck at this css and "look" stuff ;) But at least I try ;)

**Comment by fjalvingh** [comment]
Closing as I am trying to incorporate Bulma principles without integrating with it.

**Comment by YoeriNijs** [comment]
I just drop a line here: maybe you want to take a look to [Tachyons](https://tachyons.io). It is like Bulma, but maybe easier to incorporate in your framework.
