### ISSUE TITLE
Create a normal look for the FileUpload component

### ISSUE THREAD

**Issue by fjalvingh** [fjalvingh/domui#51]
![image](https://user-images.githubusercontent.com/1500452/32123769-b9f7d2da-bb65-11e7-8e76-98301c4e09fd.png)

is just too bloody ugly.

We should have two separate looks:

* One for when it loads only one file. In that case the main component can be inline and should be simple
* One for when it loads multiple files, in which case the presentation should be tabular.

**Comment by YoeriNijs** [comment]
The main thing is: what do you want to see as a user? I think the user wants to assure himself that the file is or files are selected. Because of this, using two separate looks is not the goal itself.

Today, most UI frameworks use one upload area for both selecting one and multiple files. In some cases, the area supports drag and drop as well. Imho Telerik has a nice example of a file upload component fits the task well: http://demos.telerik.com/kendo-ui/upload/index. What is your opinion about this?

**Comment by fjalvingh** [comment]
Fixed; described in https://etc.to/confluence/display/DOM/FileUpload+components. Replaced the old component with two separate new ones; one to load a single file, the other for multiple files:

![image](https://user-images.githubusercontent.com/1500452/32857826-7f0de252-ca49-11e7-8596-35bfcaededc6.png)

**Comment by fjalvingh** [comment]
BTW: dragging files on top of the button works too.
