### ISSUE TITLE
Possible bug found in LookupForm or ComboLookup2

### ISSUE THREAD

**Issue by YoeriNijs** [fjalvingh/domui#6]
For an application, we have made a DomUI's LookupForm component with a mandatory property field. In that form, we added two ComboLookup2's. Next, we selected one thing as the default value for the first ComboLookup2, and we have set this lookup to mandatory. This may look like this:

```
LookupForm<Case> lookupForm = m_lookupForm = new LookupForm<>(Case.class);
add(lookupForm);

ComboLookup2<CadCachedCaseType> caseTypeLookup = m_caseTypeLookup;
CadCachedCaseType initialCaseType = m_cadCachedCaseTypes.get(0);
caseTypeLookup.setValue(initialCaseType);
caseTypeLookup.setMandatory(true);

...
```
The CaseTypeLookup and the second ComboLookup2 will be added as manual property label. For instance:

```
lookupForm.addManualPropertyLabel(Case.pCASETYPEDEFINITION, new AbstractLookupControlImpl(caseTypeLookup) {
	@Nonnull
	@Override
	public AppendCriteriaResult appendCriteria(@Nonnull QCriteria<?> crit) throws Exception {
		CadCachedCaseType type = caseTypeLookup.getValue();
		if(null == type) {
			return AppendCriteriaResult.EMPTY;
		}
		crit.eq(Case.pCASETYPEDEFINITION, getSharedContext().getInstance(CaseTypeDefinition.class, type.getId()));
		return AppendCriteriaResult.VALID;
	}
});

```
Everything works fine initially. However, when one uses the erase button and selects another value for the first ComboLookup2 (i.e. the CaseTypeLookup) and clicks search, and finally selects the primary value and searches again, the selected object in the code does not correspond to the displayed value anymore. In other words, we have selected value x, but the code 'thinks' we have selected x-1. 

I tried to debug this problem and found that the setMandatory is responsible for this behavior. If I comment this method, everything works fine all the time. Therefore, I believe there is a possible bug in the LookupForm or the ComboLookup2.

**Comment by fjalvingh** [comment]
It looks like the code is missing something. LookupForm is one of the oldest components, and these often have sh*tty interfaces. I have not yet created a better one, so we have to bear its idiosyncrasies..

The problem here seems to be that mandatory property, because that is not directly compatible with the concept of "clearing" a search input: if you clear that input its value should become null, but when a control is mandatory the results of setting the value to null are not well defined, so this might lead to odd results.

What at the very least should be done is to implement the "clearInput()" method of the AbstractLookupControlImpl anonymous class; you should then put in the required default value instead of null. This might fix the issue already.

In the initial test case I wrote for this (ITTestLookupForm1) just pressing clear, then search would give a "mandatory" error - even though the screen was clearly filled in with a value. This seems to be another form of the same error you are describing. Adding a clearInput() to that makes the issue disappear. Perhaps you can try that too? Something like:
    
    @Override public void clearInput() {
        CadCachedCaseType initialCaseType = m_cadCachedCaseTypes.get(0);
        caseTypeLookup.setValue(initialCaseType);
    }

I will try to add a check to the components themselves so that they report an error when they try to set a mandatory component to null.

See commit ce3348dada8d667a2131b1525845d62e32e0a69f for the failing test and f1713b72622ab2057ddb6c8098b5782d078959d1 for what seems to be the workaround. You can (hopefully) also play around with the test form on the test/demo app:

https://etc.to/demo/to.etc.domuidemo.pages.test.componenterrors.LookupForm1TestPage.ui?$cid=0NyY7CIC0000_aVs1ju007Fj.c2

**Comment by fjalvingh** [comment]
The second test page, 
https://etc.to/demo/to.etc.domuidemo.pages.test.componenterrors.LookupForm2TestPage.ui?$cid=0NyY7CIC0000_aVs1ju007Fj.c2

now throws an exception with a proper message when this happens.
